### ISSUE TITLE
Make SRP6 implementation usable outside of Gomaggus

### ISSUE THREAD

**Issue by gtker** [Kangaroux/gomaggus#19]
I'm not sure how Go package management works, so I'm not sure if this is already possible.

As part of the blog post at https://gtker.com/implementation-guide-for-the-world-of-warcraft-flavor-of-srp6 I want to make it as easy as possible for people to avoid implementing the full algorithm from scratch when it isn't necessary. This is primarily achieved by just making it easier to use existing libraries in as many languages as possible.

When it's done I'll add your implementation to the list at https://gtker.com/implementation-guide-for-the-world-of-warcraft-flavor-of-srp6/#ensure-that-you-actually-need-to-implement-this-from-scratch to make it easier for other people to discover. I'll add links under the `Implementations` headers as well, I just wanted to make sure that the links weren't instantly dead if you had to move things in order to make it easier to use.

I also wanted to link the only other Go WoW server that I know of at https://github.com/Gophercraft/core, just in case it might be helpful. EDIT: Embarrassingly enough I can now see that you have open issues on Gophercraft, so you probably already know about it. :)

**Comment by Kangaroux** [comment]
Hi @gtker sorry for the late response. I will need to move the srp pkg to its own repo and do a bit of cleanup, I'll follow up when that's done.

**Comment by Kangaroux** [comment]
https://github.com/Kangaroux/go-wow-srp6

Not sure if it's worth mentioning but I think `testdata/` in the srp repo isn't necessary and could be replaced with the test inputs from the guide. That is an artifact of an earlier implementation.

**Comment by gtker** [comment]
Cool, thanks for adding additional docs as well for those unfamiliar with Go package management.

I have added it to the blog post at https://gtker.com/implementation-guide-for-the-world-of-warcraft-flavor-of-srp6/#ensure-that-you-actually-need-to-implement-this-from-scratch as well as the individual implementations.

I couldn't find the client implementation, nor the header encryption/decryption. Could you let me know if you add those and I'll update the blog?

**Comment by Kangaroux** [comment]
I've only built and tested the wrath headers but I can add those

**Comment by gtker** [comment]
As long as it works it would probably be helpful. :)

**Comment by Kangaroux** [comment]
Done. Header impl is available in v1.1.0, also updated references in gomaggus
